A/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls',namespace='home')),
    path('account/', include('account.urls',namespace='account')),
]

account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    path('register/',views.Register.as_view(),name='register'),
    path('login/',views.User_login.as_view(),name='login'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
    path('profile/<int:user_id>',views.UserProfileView.as_view(),name='user_profile'),
    path("follow/<int:user_id>/", views.UserFollowView.as_view(), name="user-follow"),
    path("unfollow/<int:user_id>/",views.UserUnFollowView.as_view(),name="user-unfollow"),
]

home/urls.py
from django.urls import path
from . import views

app_name='home'
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('post/<int:post_id>/<slug:post_slug>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/delete/<int:post_id>/',views.PostDeleteView.as_view(),name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/create', views.PostCreateView.as_view(), name='post_create'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<style>
  .jumbotron{
    padding:20px;
    margin-bottom:20px;
    background-color:#e9ecef;
 
  }


</style>

</head>
<body>
    {% block vv %}{% endblock vv %}
    {% include "messages.html" %}
    {% include "navbar.html" %}
    <div class='jumbotron'>
    {% block content %}{% endblock content %}
    </div>
</body>
</html>

templates/messages.html
{% if messages %}
{% for message in messages  %}

{{ message }}

{% endfor %}

{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">

      
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href='{% url "home:home" %}'>Home</a>
            {% if  request.user.is_authenticated %}
            <a class="nav-link active" aria-current="page" href='{% url "account:user_profile" request.user.id %}'>profile</a> 
            <a class="nav-link active" aria-current="page" href='{% url "account:logout" %}'>Logout</a> 
            {% else %}
            <a class="nav-link active" aria-current="page" href='{% url "account:register" %}'>Register</a>
            <a class="nav-link active" aria-current="page" href='{% url "account:login" %}'>Login</a>
            {% endif %}
          </li>



        </ul>
      </div>
    </div>
  </nav>